"""inadd

Revision ID: 4e2f2ee4c8d2
Revises: 
Create Date: 2024-12-14 19:13:25.296723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import Base


# revision identifiers, used by Alembic.
revision: str = '4e2f2ee4c8d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
